print("                      ___..............._")
print("             __.. ' _'.\"\"\"\"\"\"\\\"\"\"\"\"\"\"\"- .`-._")
print(" ______.-'         (_) |      \\           ` \\`-. _")
print("/_       --------------'-------\\---....______\\__`.`  -..___")
print("| T      _.----._           Xxx|x...           |          _.._`--. _")
print("| |    .' ..--.. `.         XXX|XXXXXXXXXxx==  |       .'.---..`.     -._")
print("\_j   /  /  __  \  \        XXX|XXXXXXXXXXX==  |      / /  __  \ \        `-.")
print(" _|  |  |  /  \  |  |       XXX|""'            |     / |  /  \  | |          |")
print("|__\_j  |  \__/  |  L__________|_______________|_____j |  \__/  | L__________J")
print("     `'\ \      / ./__________________________________\ \      / /___________\\")
print("        `.`----'.'   dp                                `.`----'.'")
print("          `\"\"\"\"'                                         `\"\"\"\"'")
print("")
print("------------------------------------------------")
print("Thank you for visiting https://asciiart.website/")
print("This ASCII pic can be found at")
print("https://asciiart.website/index.php?art=transportation/cars")
